### PR TITLE
[r6] Add 4 files, some small corrections

### PR DESCRIPTION
**Pull request by ktmf01**
This adds 4 mono files. 60 is just a mono file, 61-63 have short bursts of high-frequency sine waves added to speech to trigger predictor overflow in decoders that do not use 64-bit ints when appropriate

File 26, 27 and 55 had small changed to their metadata as I came across a decoder (Symphonia) that was much more strict than libFLAC and warned me about some things that were not strictly compliant with the specification

### CODE REVIEW

**Comment by ktmf01** [comment]
I'm marking this as draft as I found a potential problem with file 63. It has a few residual samples larger than 2^31, which makes ffmpeg complain.

**Comment by ktmf01** [comment]
The issue with ffmpeg has been fixed as of https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/296d3bbe167f06168ac54724626006b43002833f I suppose ffmpeg 5.1 will be the first release able to play file 63.

**Comment by ktmf01** [comment]
I've just force-pushed this PR to add a LICENSE.txt and to add a license statement to README.txt

**Comment by JeromeMartinez** [comment]
@ktmf01 just to be clear, the encoder input is also CC0? If not, the output can not be CC0, more a "fair use".

**Comment by ktmf01** [comment]
Obviously I cannot guarantee all files are completly free of any copyright, but I think I made a reasonable effort to use only material either free of copyright, material licensed under CC0 where it seems reasonable to believe the uploader created the material, or material I created myself. Being able to state that these files are licensed CC0 was the reason all files were remade for revision 5, I just forgot to state it in the README.

In an attempt to make this CC0-claim reasonably verifyable, I'll list my sources.

* All files feature text-to-speech generated by Amazon Polly. To the best of my knowledge there rests no copyright on this as there is no artistic input in text-to-speech. Furthermore, [Amazon Polly FAQ states the following](https://aws.amazon.com/polly/faqs/#):

> **Q: Who owns Polly recordings?**
> As between you and AWS, your Polly output belongs to you. If you input text into Polly that belongs to a third party, we require that you have the rights to do so. For more information, please see our [Customer Agreement](https://aws.amazon.com/agreement/) and how it handles “Your Content”

* The recording of a tuning orchestra used in tracks 1 - 10 was made by myself with permission of the orchestra.
* The recording of a drum kit used in tracks 11 - 23 was made by myself of myself performing.
* The recording of birdsong used in tracks 24 - 27 was published under CC0 here: https://freesound.org/s/385279/
* The music used in tracks 28 - 37 was published under CC0 here: https://freesound.org/s/593792/
* The music used in track 44 was published under CC0 here: https://freesound.org/s/593851/ It was upmixed to 7.1 surround using Foobar2000 with foo_dsp_fsurround (FreeSurround)
* The music used in tracks 45 - 54 was published under CC0 here: https://freesound.org/s/140481/
* The music used in track 55 was published under CC0 here: https://freesound.org/s/441302/
* The music used in tracks 56 - 59 was published under CC0 here: https://freesound.org/s/592632/
* Tracks 38 - 43 and 60 - 63 feature only text-to-speech sources.

**Comment by mcr** [comment]
I think you have gone way above and beyond due diligence here. Thank you.
Merge away!

**Comment by JeromeMartinez** [comment]
> I think you have gone way above and beyond due diligence here.

Agreed.

**Pull request merged**
